In [1]:
import torch
import numpy as np

In [20]:
x = torch.randn(5, 3)
y = -99*torch.rand(5,3)

In [21]:
print(x)

tensor([[ 1.5568,  1.7817, -0.0585],
        [-0.1102, -0.7366, -0.8254],
        [-2.5701,  0.3645,  0.7269],
        [ 1.7640, -1.2825,  0.1227],
        [ 0.5386,  0.1989,  0.0610]])


In [22]:
print(y)

tensor([[-10.6328, -95.6246, -13.3005],
        [-97.9882,  -9.7028, -24.0946],
        [ -4.5923, -62.7251,  -8.8939],
        [-52.0988, -76.9938, -12.7576],
        [-68.3151, -51.7393, -49.4241]])


In [24]:
zero_inds = (x<0).float()
nzero_inds = (x>=0).float()
print(zero_inds)
print(nzero_inds)

tensor([[0., 0., 1.],
        [1., 1., 1.],
        [1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 0.],
        [0., 0., 0.],
        [0., 1., 1.],
        [1., 0., 1.],
        [1., 1., 1.]])


In [28]:
torch.mul(y, nzero_inds)+torch.mul(x,zero_inds)

tensor([[-1.0633e+01, -9.5625e+01, -5.8486e-02],
        [-1.1023e-01, -7.3662e-01, -8.2539e-01],
        [-2.5701e+00, -6.2725e+01, -8.8939e+00],
        [-5.2099e+01, -1.2825e+00, -1.2758e+01],
        [-6.8315e+01, -5.1739e+01, -4.9424e+01]])

In [26]:
torch.mul(x,inds)

tensor([[ 0.0000,  0.0000, -0.0000],
        [-0.0000, -0.7366, -0.8254],
        [-0.0000,  0.3645,  0.0000],
        [ 1.7640, -1.2825,  0.0000],
        [ 0.0000,  0.0000,  0.0000]])

In [27]:
torch.mul(y, nzero_inds)

tensor([[-10.6328, -95.6246,  -0.0000],
        [ -0.0000,  -0.0000,  -0.0000],
        [ -0.0000, -62.7251,  -8.8939],
        [-52.0988,  -0.0000, -12.7576],
        [-68.3151, -51.7393, -49.4241]])

In [31]:
z = torch.FloatTensor(x.shape).uniform_(-10, 10)

In [32]:
print(z)

tensor([[ 7.5608, -1.4678,  9.3779],
        [ 5.4386,  1.9823, -3.7757],
        [ 3.7084, -5.3523, -2.5741],
        [-6.9177,  7.6486,  0.9215],
        [ 8.2865, -3.0896, -3.5484]])


In [35]:
torch.max(z).item()

9.377946853637695