In [1]:
import torch
import numpy as np

In [2]:
out_features = 4
in_features = 16

In [12]:
g = np.arange(in_features*out_features).reshape((in_features, out_features))
print(g.shape)
print(g)

(16, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]
 [40 41 42 43]
 [44 45 46 47]
 [48 49 50 51]
 [52 53 54 55]
 [56 57 58 59]
 [60 61 62 63]]


In [13]:
max_prev_g = np.arange(in_features)
print(max_prev_g.shape)
print(max_prev_g)

(16,)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [17]:
np.einsum('ij,i -> ij', g, max_prev_g)


array([[  0,   0,   0,   0],
       [  4,   5,   6,   7],
       [ 16,  18,  20,  22],
       [ 36,  39,  42,  45],
       [ 64,  68,  72,  76],
       [100, 105, 110, 115],
       [144, 150, 156, 162],
       [196, 203, 210, 217],
       [256, 264, 272, 280],
       [324, 333, 342, 351],
       [400, 410, 420, 430],
       [484, 495, 506, 517],
       [576, 588, 600, 612],
       [676, 689, 702, 715],
       [784, 798, 812, 826],
       [900, 915, 930, 945]])